language: node_js
node_js: stable
sudo: false
before_install:
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
# before_script:
#   - npm update -g npm

matrix:
  include:
    -
      stage: test
      script:
        # Run test script, depending on istanbul install
        - "test -n $(npm -ps ls istanbul) || npm test"
        - "test -z $(npm -ps ls istanbul) || npm run-script test-travis"
      after_script:
        - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
    -
      stage: release
      if: tag =~ ^v #release all vX.X.X tags
      script:
        - "npm pack"
      after_script:
        - "release-it"